# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269208852d74765c8347f4cdb61a702ba7beb52e291122586317db6b67a5f19427adf3246bd580a662010f3860011be1860f340b866a17d574de44b7afdef223

test:
  secret_key_base: c4726399c3c0048474bf66f1fce5d0ffce2c3136c6accc73c3420e4a5c09eb4a92c8699b73a58645ea8c70f603488a8add2df8968608b727144b6957425c075e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
